"""Writes the narrative chapters of the report from the facts package.

The model sees only (a) the cited narrative notes gathered by the research agent and
(b) the rounded numerical results. It has no web access here, so every number it writes
must come from those facts; the report then audits the numbers it used.
"""
from __future__ import annotations

import json
from typing import Callable, Optional

from .llm import DEFAULT_MODEL, Usage, make_client, run_submit_loop

WRITER_SYSTEM = """You are writing chapters of a quantitative volcanology report in the style of a careful MSc thesis ("From magma compressibility to surface deformation at <volcano>"). The physical framework, tables and figures are generated by code; you write the prose.

Style:
- Formal academic English, precise and measured, third person. No marketing language, no bullet lists inside prose, no rhetorical questions.
- Every factual statement about the volcano carries an (Author, Year) citation, using ONLY the reference keys provided. Never cite anything else, except the method itself, which is cited as "Freya Mohammadian (2026)".
- Use ONLY numbers that appear in the FACTS JSON (you may round them, convert units, or express a ratio of two given numbers). Do not introduce any other number. If a quantity is not in the facts, describe it qualitatively or say it is not constrained.
- Conditional phrasing for model results: e.g. "under the adopted volatile budgets, the modelled magma is gas-undersaturated at 5 km", never "the reservoir is gas-free".
- Inputs with status "D" are generic defaults, not volcano-specific: whenever a conclusion depends on them, say so explicitly. Status "A" values are adopted representative values; "U" values are detection limits.
- If the published interpretation of the deformation source is hydrothermal, treat the magmatic calculation at that geometry as a hypothetical magmatic end-member and say so.
- Penny-crack configurations whose thin-crack condition is "violated" are stiff-walled idealisations, not sills of this volcano: never quote their r_V or pressures as predictions for the volcano; quote r_V ranges split by geometric status.
- The 10 MPa screen is a reference screening threshold used to rank configurations, not a failure criterion.
- The cavity-volume change and overpressure needed for a given uplift are fixed by the elastic problem; the injected magma volume depends on the volatile state, datum and compressibility branch. Spatial wavelength constrains depth within a given source model; amplitude is non-unique.
- Formatting: plain text paragraphs separated by a blank line. Subsection headings on their own line starting with "## ". Chemical formulas and symbols with <sub>/<sup> tags, e.g. H<sub>2</sub>O, CO<sub>2</sub>, r<sub>V</sub>, β<sub>m</sub>, 10<sup>6</sup> m<sup>3</sup>. Italic with <i>..</i>. No other markup, no Markdown tables.
Finish by calling the submit tool exactly once."""

PART_A = {
    "abstract": "Abstract, 300-450 words: problem, method (seven-step chain, EVo, Mogi/Yang/Fialko), data provenance, the key quantitative results (saturation state, r_V ranges split by geometry, uplift for the scenario volumes, injected volume for the target uplift by depth, dominant sensitivities), and the main limitation.",
    "intro_volcano": "Section 1.2, 250-450 words: the volcano, its activity, the reason the compressibility question matters here (unrest, monitoring, hazard). Cited.",
    "aims": "Section 1.3, 150-300 words: aim and five research questions RQ1-RQ5 (volume partitioning; forward predictions; detectability and pressure demand; consistency with the published source if any; sensitivity), adapted to this volcano, written as a short paragraph followed by the five questions each on its own paragraph starting 'RQ1 -' etc.",
    "ch2_setting": "Section 2.1-2.2, 250-500 words: geodynamic setting and eruptive history. Cited.",
    "ch2_magmas": "Section 2.3, 200-400 words: the magma series and its evolution. Cited.",
    "ch2_plumbing": "Section 2.4, 250-500 words: the plumbing system, each storage level with its evidence, and how they map onto the modelled levels. Cited.",
    "ch2_volatiles": "Section 2.5, 250-450 words: volatile budgets and temperatures, what melt inclusions do and do not record, and the status (M/U/A/D) of the key inputs. Cited.",
    "ch2_unrest": "Section 2.6, 200-500 words: hydrothermal system, unrest and ground deformation history, and the published source model (or its absence) with its interpretation and the pressure-datum issue for shallow sources. Cited.",
    "ch2_synthesis": "Section 2.7, 120-250 words: the conceptual scheme adopted for the model (levels, resident/injected magmas, the published source).",
}
PART_B = {
    "res_state": "Section 5.1, 200-400 words: magmatic state of every reservoir (P, Psat, saturation, gas fraction), the vapour of any saturated reservoir; compare computed saturation pressures with published pressures where available (independent check).",
    "res_partitioning": "Section 5.2-5.3, 250-450 words: compressibilities, r_V for all configurations with ranges split by geometric status, expressed fractions, frozen vs equilibrium branch.",
    "res_uplift": "Section 5.4, 200-400 words: predicted uplift at centre, 1 and 2 km; depth control on amplitude and wavelength; ratio u(2 km)/u(0) as a depth indicator within a source model.",
    "res_inverse": "Section 5.5, 200-400 words: injected volume and overpressure needed for the target uplift, ordering by geodetic cost, the screen, and the coupling of screened rows to the thin-crack violation.",
    "res_sensitivity": "Section 5.6, 300-600 words: volatile budget (Scenario B, depth dependence with multipliers stated), pressure datum and H2O of the shallow source if computed, elastic parameters, density, redox, aspect ratio.",
    "discussion": "Chapter 6, 700-1200 words with '## ' subsections: which sources produce observable deformation; why deep recharge is weakly expressed; the role of gas; hydrothermal vs magmatic pressurisation where relevant; limitations (half-space, topography, ideal gas, single reservoir, generic defaults used); what would discriminate (gas chemistry, seismicity, thermal output). Cite the volcano literature where relevant.",
    "conclusions": "Chapter 7, 500-900 words: answers to RQ1-RQ5 (one paragraph each, starting 'RQ1 -'), implications for monitoring (volume and pressure thresholds by depth), and future work (3-5 items, as prose).",
}


def _schema(keys: dict) -> dict:
    return {"type": "object", "properties": {k: {"type": "string", "description": d} for k, d in keys.items()},
            "required": list(keys)}


def write_chapters(ds, facts: dict, api_key: Optional[str] = None, model: str = DEFAULT_MODEL,
                   on_event: Callable[[str], None] | None = None, usage: Usage | None = None) -> dict:
    say = on_event or (lambda s: None)
    client = make_client(api_key)
    refs = [r.key for r in ds.references]
    notes = json.dumps(ds.narrative, ensure_ascii=False, indent=1)
    facts_s = json.dumps(facts, ensure_ascii=False, separators=(",", ":"))
    common = (f"VOLCANO: {ds.name}\n\nREFERENCE KEYS YOU MAY CITE:\n{json.dumps(refs, ensure_ascii=False)}\n\n"
              f"RESEARCH NOTES (cited summaries gathered from the literature):\n{notes}\n\n"
              f"FACTS (all numbers you may use):\n{facts_s}\n")
    out = {}
    say("Writing the abstract, introduction and the volcanic-system chapter")
    out.update(run_submit_loop(client, model=model, system=WRITER_SYSTEM,
                               user=[{"type": "text", "text": common, "cache_control": {"type": "ephemeral"}},
                                     {"type": "text", "text": "Write the following sections:\n" +
                                      "\n".join(f"- {k}: {v}" for k, v in PART_A.items())}],
                               force_submit=True,
                               submit_name="submit_sections", submit_description="Submit the written sections.",
                               submit_schema=_schema(PART_A), on_event=say, usage=usage, max_tokens=32000))
    say("Writing the results, discussion and conclusions")
    out.update(run_submit_loop(client, model=model, system=WRITER_SYSTEM,
                               user=[{"type": "text", "text": common, "cache_control": {"type": "ephemeral"}},
                                     {"type": "text", "text": "Write the following sections:\n" +
                                      "\n".join(f"- {k}: {v}" for k, v in PART_B.items())}],
                               force_submit=True,
                               submit_name="submit_sections", submit_description="Submit the written sections.",
                               submit_schema=_schema(PART_B), on_event=say, usage=usage, max_tokens=32000))
    return out


def offline_chapters(ds, facts: dict) -> dict:
    """Plain, factual placeholder text used when no API key is given (offline demo)."""
    cfg = facts["configurations"]
    lv = ", ".join(f"{L['name']} ({L['depth_km']['value']} km, {L['resident'].lower()})" for L in facts["inputs"]["levels"])
    sat = [s for s in facts["magmatic_states"] if s["role"] == "resident" and s["saturated"]]
    txt = {k: "" for k in list(PART_A) + list(PART_B)}
    txt["abstract"] = (f"This report applies the seven-step compressibility-to-deformation chain to {ds.name}. "
                       f"The modelled storage levels are {lv}. "
                       f"Under the adopted volatile budgets, {len(sat)} of the resident magmas are gas-saturated at their storage pressure. "
                       "[Offline mode: the narrative chapters are written by the language model when an API key is supplied; "
                       "all tables and figures below are complete.]")
    for k, v in ds.narrative.items():
        if k in ("setting", "history"):
            txt["ch2_setting"] += v + "\n\n"
        elif k == "plumbing":
            txt["ch2_plumbing"] += v + "\n\n"
        elif k.startswith("volatiles"):
            txt["ch2_volatiles"] += v + "\n\n"
        elif k in ("unrest", "deformation", "hydrothermal"):
            txt["ch2_unrest"] += v + "\n\n"
        elif k == "magma_series":
            txt["ch2_magmas"] += v + "\n\n"
    rv = [c["rV"] for c in cfg]
    txt["res_partitioning"] = f"Across all configurations r<sub>V</sub> ranges from {min(rv):.3g} to {max(rv):.3g} (see Table 5.2 for the geometric status of each)."
    return txt
